name: "CI"
on:
  push:
    branches:
      - "master"
      - "hotfix/**"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libssl-dev zlib1g-dev

      - name: Clone ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          sudo ./install.sh

      - name: Install Ruby
        run: |
          ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Add Ruby to PATH
        run: echo "/opt/hostedtoolcache/Ruby/3.1.4/x64/bin" >> $GITHUB_PATH

      - name: Verify Ruby Installation
        run: ruby --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm install && npm run build

      - name: Test Site
        run: bash tools/test.sh
